# Generated by Django 4.2.7 on 2023-12-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersatisfactionmetrics', '0005_response_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
