# Generated by Django 5.0.9 on 2024-10-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersatisfactionmetrics', '0006_question_max_label_question_min_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(
                choices=[
                    ('en', 'English'),
                    ('nl', 'Dutch'),
                    ('fr', 'French'),
                    ('de', 'German'),
                    ('es', 'Spanish'),
                    ('pt', 'Portuguese'),
                    ('it', 'Italian'),
                    ('pl', 'Polish'),
                    ('hi', 'Hindi'),
                    ('ar', 'Arabic'),
                    ('ru', 'Russian'),
                    ('uk', 'Ukrainian'),
                    ('no', 'Norwegian'),
                    ('sv', 'Swedish'),
                    ('fi', 'Finnish'),
                    ('da', 'Danish'),
                    ('zh-hans', 'Chinese'),
                ],
                default='en',
                max_length=255,
            ),
        ),
    ]
