# Generated by Django 4.2.7 on 2026-08-18 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customersatisfactionmetrics', '0008_response_created_at_response_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Touchpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_days', models.PositiveIntegerField(default=84)),
                ('cooldown_scope', models.CharField(
                    choices=[('GLOBAL', 'Across all touchpoints'), ('TOUCHPOINT', 'This touchpoint only')],
                    default='GLOBAL', max_length=20)),
                ('scope_cooldown_days', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('survey', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='touchpoints',
                    to='customersatisfactionmetrics.survey')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=128)),
                ('scope_key', models.CharField(blank=True, max_length=255)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('touchpoint', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='impressions',
                    to='customersatisfactionmetrics.touchpoint')),
                ('user', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shown_at'],
                'indexes': [
                    models.Index(fields=['user', 'shown_at'], name='customersat_user_id_1d98fa_idx'),
                    models.Index(fields=['session_id', 'shown_at'], name='customersat_session_0adf3f_idx'),
                    models.Index(fields=['scope_key', 'shown_at'], name='customersat_scope_k_7f6884_idx'),
                ],
            },
        ),
    ]
