# Generated by Django 4.2.7 on 2026-08-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customersatisfactionmetrics', '0009_touchpoint_impression'),
    ]

    operations = [
        migrations.AddField(
            model_name='impression',
            name='content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='impression',
            name='object_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='response',
            name='content_type',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='response',
            name='object_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
