version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./db.sqlite3:/code/db.sqlite3
      - ./customersatisfactionmetrics:/code/customersatisfactionmetrics
    ports:
      - "8000:8000"
