# Generated by Django 4.2.7 on 2023-11-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customersatisfactionmetrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="response_type",
            field=models.CharField(
                choices=[
                    ("CSAT", "Customer Satisfaction"),
                    ("NPS", "Net Promoter Score"),
                    ("CES", "Customer Effort Score"),
                    ("GENERIC", "Generic Survey"),
                ],
                max_length=22,
            ),
        ),
    ]
