# Generated by Django 4.2.7 on 2023-11-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customersatisfactionmetrics", "0002_alter_response_response_type"),
    ]

    operations = [
        migrations.AlterModelOptions(name="question", options={"ordering": ["order"]},),
        migrations.AddField(
            model_name="question", name="order", field=models.IntegerField(default=0),
        ),
    ]
