# Generated by Django 4.2.7 on 2023-11-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customersatisfactionmetrics", "0003_alter_question_options_question_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
